HIT137 Assignment 1
Conor Ward S359350
Arsyl Galleno S303886
Ashrie Talipauan S372245
Topic – Text Processing Models, Natural Language Processing
Natural Language Processing (NLP) began in the 1950’s in systems such as machine language translation,evolving into the form of generative artificial intelligence (AI) such as ChatGPT which is seen today [1]. NLP has multiple uses in many fields including, Education, generative artificial intelligence and general purpose programming. In essence, the purpose of NLP is to take human language that is inserted into a computer and subsequently analyze it for a multitude of purposes. However with its evolution and the rise of technologies such as generative AI this has impacted society in a variety of ways. In addition to creating new ethical considerations in multiple domains.
In the modern era, the use of NLP’s has crept into most facets of computing. This includes information retrieval via the use of a search engine and  [2]  abilities such as the spell check feature prominent within the Microsoft Office suite [3]. NLP has been utilized for the creation of generative AI platforms such as ChatGPT. A wide range of human created text is fed into the model, allowing it to learn the mannerisms in which humans write such as the associations between words, sentence structure and tone [4]. With the gathered information users are able to insert a prompt into the ChatGPT system and be returned with a generated response that follows the cadence, sentence structure and tone that is expected with human language. 
By and large NLP’s have created an overall positive influence on society. In which previously laborious tasks of information processing and data input are now streamlined into processes completed within seconds rather than hours or days. However, continuing within the realm of generative AI, an ethical dilemma has arisen especially when considering medical, education and political fields. These tools are able to be used to create text that appears to be written by a human author.[5]. Theoretically student’s have been able to input a prompt into a generative AI model, conduct some minor edits and submit a piece of writing that will pass plagiarism detectors [5]. This results in the individual having an unfair advantage over their peers who also are conducting the assigned task in the traditional method. This has resulted in the need for improved plagiarism detectors to ensure accountability amongst students and a safeguard for the educational system. In addition to detecting fake news or reports in both the political and medical fields. 
Python is a programming language designed for general purpose programming. The natural language toolkit (NLTK) is a Python package that is able to be used for natural language processing. This tool allows users to analyze human readable text and process it into structured data to be utilized by python [6]. The data that is imputed to Python. Utilizing this toolbox allows users to conduct various tasks such as seeking frequently used terms or phrases, make dispersion plots and finding sequences of words that show up often known as collocations.
There are several libraries such as Nlpdotnet Tokenizer [7] used as tools for the tokenization of language. This involves dividing bodies of text into small units or tokens. Tokenization is often the first step within a NLP procedure converting the inputted unstructured data into structured data that the python system is able to process. After a piece of text has been tokenized, other libraries are able to be used within Python to analyse the text to the desire of the user. Such libraries include Gensim for topic modeling, PyNLPL for building simplistic models and TextBlob for a variety of NLP operations [8] 
Another notable library called Stanza NLP Library that provides advanced NLP tools specifically designed for the biomedical industry, which improves the skills of NER and syntactic analysis. These tools are based on neural network models and can effectively manage the complexities of clinical notes and biological literature. The library's solutions have been shown to produce state-of-the-art results, are easy to use, and work particularly well with GPU acceleration. They are trained on specialised corpora, such as the CRAFT and GENIA treebanks.
These libraries play a crucial role in advancing natural language processing (NLP) in various industries. They are particularly helpful in analyzing clinical texts in the healthcare sector, as well as in customer service and marketing to understand customer sentiments and trends. Scholarly literature has shown that these libraries are powerful in handling both general and specialized NLP tasks, thus proving their wide applicability and impact on the field.
In summary, NLP is a very useful tool derived from the python programming language, through its wide applications in multiple fields. NLP is used in information retrieval, as well as the development of generative Artificial Intelligence Systems (ChatGTP).  NLP also uses vast libraries, including NLPdotnet Tokenizers which organizes unstructured data for processing. With its vast improvements in fields such as education, there also arose ethical concerns. Especially when being used in academia, students could gain an unfair advantage when assisted by Artificial Intelligence. In addition to fake news or reports in both the medical and political fields. Overall, Natural Language Processing has had a positive impact on society today. This has enabled the development of streamlined technology in multiple fields. With the emergence of NLP, and the versatility of the python language, developers will continue to harness its advantages to improve Society as a whole. However, this has created a need to safeguard against plagiarism and fake news or reports with improved AI plagiarism detectors.
References
[1] W. W. Chapman, P. M. Nadkarni and L. Ohno-Machado, “Natural language processing: an introduction,” JAMIA, p. 1, 2011. 
[2] E. Cambria and B. White, “Jumping NLP Curves: A Review of Natural Language Processing Research,” IEEE Computational Intelligence Magazine, vol. 9, no. 2, pp. 48-57, May 2014. 
[3] K. Kukich, “Techniques for Automatically Correcting Words in Text,” ACM Computing Surveys, vol. 24, no. 4, pp. 337-439, 1992. 
[4] D. Kalla, S. Kuraku, F. Samaah and N. Smith, “Study and Analysis of Chat GPT and its Impact on Different Fields of Study,” International Journal of Innovative Science and Research Technology, vol. 8, no. 3, pp. 827-833, March 2023. 
[5] M. King, J. McMillan and H. Zohny, “Ethics of generative AI,” Journal of Medical Ethics, vol. 49, pp. 79-80, 2023. 
[6] J. Jablonski, “Natural Language Processing With Python's NLTK Package,” Real Python, [Online]. Available: https://realpython.com/nltk-nlp-python/. [Accessed 20 03 2024].
[7] R. Janani and S. Vijayarani, “Text Mining: Open Source Tokenization Tools – An Analysis,” Advanced Computational Intelligence: An International Journal, vol. 3, no. 1, pp. 37-47, 2016. 
[8] A. L. Saueth Saabith and T. Vinothraj, “Popular Python Libraries And Their Application Domains,” International Journal of Advance Engineering and Research Development, vol. 7, no. 11, pp. 18-26, November 2020. 

